In [21]:
import numpy as np 
import pandas as pd

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

from keras.models import Sequential, load_model, Model
from keras.layers import Dense, Activation, Dropout, Input, LSTM, Reshape, Lambda, RepeatVector
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras.callbacks import EarlyStopping
from keras.layers import Dropout
from keras.optimizers import Adam

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import mean_absolute_error

from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import Ridge

In [25]:
data_path = 'Outputs/total_array.csv'
raw_data = np.loadtxt(data_path, delimiter=',', skiprows=0)

In [23]:
print(raw_data.shape)
num_sample = raw_data.shape[0]
num_time_steps = 10
x_dim = 210
y_dim = 1

(2121, 211)


In [27]:
scaler = MinMaxScaler(feature_range=(0, 1))
raw_data[:, 0: 11] = scaler.fit_transform(raw_data[:, 0: 11])

In [26]:
scaler_y = MinMaxScaler(feature_range=(0, 1))
scaler_y.fit(raw_data[:, 0].reshape((2121, 1)))

MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
def get_label(stock_price, pre_stock_price):
    
    if abs(stock_price - pre_stock_price)/pre_stock_price <= 0.00016:
        label = 0
    elif (stock_price - pre_stock_price)/pre_stock_price > 0.00016:
        label = 1
    else:
        label = 2
        
    return label

In [28]:
X = []
y = []

for sample in range(num_sample):
    data_input = raw_data[sample, :]
    stock_labels = raw_data[sample, 0: num_time_steps + 1]
    
    y.append(stock_labels[0])
    X.append(data_input[1:])

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)
X_train = np.array(X_train)
X_test = np.array(X_test)

In [40]:
y_binary = to_categorical(y_train)

In [7]:
print(np.array(X_train).shape)
print(X_test.shape)
print(len(y_train))

(1696, 6447)
(425, 6447)
1696


In [30]:
model = Ridge()

In [11]:
model.summary()

AttributeError: 'SGDClassifier' object has no attribute 'summary'

In [22]:
train_f1 = []
test_f1 = []

In [31]:
model.fit(X_train, y_train)
trainPredict = model.predict(X_train)
testPredict = model.predict(X_test)
    

In [43]:
print(X_test)

[[0.4138104  0.41424114 0.41430325 ... 0.         0.         0.        ]
 [0.78395557 0.78475398 0.7849752  ... 0.         0.         0.        ]
 [0.63959582 0.63956096 0.63965025 ... 0.         0.         0.        ]
 ...
 [0.53981646 0.5402764  0.54002355 ... 0.         0.         0.        ]
 [0.40164983 0.40184937 0.40468257 ... 0.         0.         0.        ]
 [0.7348369  0.73504905 0.73452924 ... 0.         0.         0.        ]]


In [32]:
trainPredict = scaler_y.inverse_transform(np.array(trainPredict).reshape((1696,1)))
y_train = scaler_y.inverse_transform(np.array(y_train).reshape((1696,1)))

In [13]:
for idx, pred in enumerate(trainPredict):
    print(pred, y_train[idx])

[2477.62720738] [2477.31]
[2399.11622767] [2399.24]
[2757.92478936] [2759.13]
[2272.74087112] [2272.23]
[2398.27186638] [2397.71]
[2713.04060047] [2713.19]
[2711.38443468] [2711.51]
[2267.68705787] [2267.56]
[2771.4671083] [2771.34]
[2841.56170236] [2841.92]
[2431.09591792] [2431.52]
[2499.61721955] [2500.83]
[2390.35375793] [2390.19]
[2723.76055586] [2723.82]
[2505.79026718] [2505.86]
[2873.82461507] [2873.69]
[2843.07282485] [2844.07]
[2177.12446862] [2176.26]
[2738.5662803] [2738.7]
[2445.53094471] [2445.35]
[2729.18945345] [2729.17]
[2648.74297079] [2648.77]
[2506.78471019] [2506.68]
[2633.29357979] [2633.45]
[2794.71947508] [2794.74]
[2899.13033705] [2898.5]
[2855.17085749] [2855.14]
[2932.54714943] [2933.58]
[2783.52589366] [2783.38]
[2886.24398735] [2886.95]
[2563.39297517] [2563.69]
[2566.47084948] [2566.42]
[2562.72730138] [2562.64]
[2723.80300866] [2723.78]
[2382.99484089] [2382.86]
[2770.22608919] [2770.67]
[2666.22083103] [2666.4]
[2603.39766871] [2603.48]
[2858.53967576] [

[2560.25850356] [2559.9]
[2602.24723179] [2601.91]
[2342.83058447] [2342.69]
[2443.16787866] [2442.95]
[2870.72429368] [2871.17]
[2710.95308419] [2711.03]
[2800.72069179] [2801.23]
[2811.19905618] [2810.99]
[2710.03269486] [2710.41]
[2507.17578187] [2507.27]
[2933.86678457] [2933.64]
[2804.66791297] [2804.83]
[2570.35702304] [2570.33]
[2666.92181085] [2666.87]
[2636.0814801] [2636.24]
[2343.48240602] [2343.16]
[2803.95576359] [2804.12]
[2393.40746446] [2393.31]
[2670.72308898] [2670.86]
[2478.91374481] [2478.21]
[2570.92073298] [2570.98]
[2713.00795308] [2713.18]
[2928.052731] [2928.39]
[2430.26544473] [2430.23]
[2460.05041585] [2459.96]
[2679.76390437] [2680.53]
[2550.6201458] [2551.26]
[2729.27353136] [2730.06]
[2389.33445175] [2389.02]
[2756.01210567] [2755.91]
[2714.96491321] [2715.33]
[2725.27491455] [2725.32]
[2620.26734189] [2620.55]
[2723.14518433] [2723.53]
[2554.89613424] [2555.5]
[2317.51062782] [2317.29]
[2342.11944572] [2341.82]
[2367.53325385] [2367.65]
[2807.44314752] [2

[2444.50034855] [2444.43]
[2207.92675714] [2207.5]
[2507.26742174] [2506.52]
[2634.24404568] [2633.8]
[2271.39333488] [2270.94]
[2372.38003386] [2372.32]
[2898.86937292] [2899.34]
[2768.49417959] [2769.]
[2251.38066084] [2250.98]
[2442.1444148] [2442.24]
[2811.32456815] [2811.29]
[2381.56089281] [2381.33]
[2655.74406626] [2655.89]
[2734.23696219] [2734.46]
[2450.72288842] [2451.01]
[2819.36630954] [2819.35]
[2930.63766527] [2930.67]
[2929.12975561] [2929.41]
[2899.75507441] [2899.73]
[2598.24257772] [2597.79]
[2342.17396628] [2341.68]
[2661.63527818] [2661.68]
[2547.2033179] [2547.34]
[2467.01501564] [2467.34]
[2561.34868465] [2561.06]
[2391.51898888] [2391.29]
[2731.79465681] [2731.74]
[2745.2965553] [2745.55]
[2694.24830491] [2694.]
[2277.30220945] [2277.21]
[2734.25256266] [2734.36]
[2910.96145844] [2911.36]
[2534.76188724] [2534.04]
[2376.54788942] [2375.92]
[2580.93018527] [2580.8]
[2790.17023598] [2790.13]
[2692.23010641] [2691.85]
[2830.75335033] [2830.75]
[2191.23310608] [2191.

[2563.59956656] [2563.51]
[2577.93692136] [2577.96]
[2572.04280048] [2571.86]
[2370.88672702] [2370.46]
[2684.18398957] [2684.34]
[2507.67330879] [2507.86]
[2585.35193539] [2585.61]
[2350.92782966] [2350.63]
[2812.73839546] [2812.66]
[2343.55796627] [2342.71]
[2722.9371635] [2722.82]
[2619.38839146] [2620.06]
[2788.48480522] [2788.42]
[2174.33365461] [2174.05]
[2596.63276922] [2596.54]
[2638.11846821] [2638.05]
[2450.38500206] [2451.05]
[2884.85953923] [2885.03]
[2282.10716658] [2281.94]
[2918.22697367] [2918.47]
[2578.79442814] [2579.]
[2773.34786827] [2773.44]
[2812.87924929] [2814.75]
[2573.73034714] [2573.9]
[2799.09758608] [2799.25]
[2810.88916333] [2811.13]
[2397.36935127] [2395.89]
[2743.22005957] [2742.81]
[2683.50137372] [2683.52]
[2343.15896662] [2341.38]
[2295.76259647] [2295.68]
[2576.27387331] [2576.17]
[2841.11973127] [2841.48]
[2494.44415786] [2494.4]
[2712.98323428] [2713.42]
[2623.39871883] [2623.21]
[2650.10913158] [2650.1]
[2631.59374962] [2632.58]
[2837.71862277] [2

In [21]:
print(confusion_matrix(y_train, np.argmax(trainPredict, axis=1)))
print(f1_score(y_train, np.argmax(trainPredict, axis=1), average='micro'))

[[170  32  50]
 [ 12 453  80]
 [ 22 101 776]]
0.8248820754716981


In [33]:
print(r2_score(y_train, trainPredict))
print(mean_squared_error(y_train, trainPredict))
print(mean_absolute_error(y_train, trainPredict))

0.999919192774502
2.9394288416345553
1.0799636447946632


In [157]:
testPredict = model.predict(X_test, batch_size=1)

In [34]:
testPredict = scaler_y.inverse_transform(testPredict.reshape((425,1)))
y_test = scaler_y.inverse_transform(np.array(y_test).reshape((425,1)))

In [16]:
for idx, pred in enumerate(testPredict):
    print(pred, y_test[idx])
    

[2467.24166634] [2468.98]
[2766.03644527] [2764.69]
[2643.80330594] [2630.34]
[2256.51290469] [2256.04]
[2439.49654273] [2445.36]
[2672.04347186] [2666.57]
[2448.92038438] [2446.43]
[2819.69315025] [2820.44]
[2678.01620458] [2678.96]
[2692.87502581] [2695.2]
[2816.46379298] [2815.38]
[2369.51089422] [2366.36]
[2572.14622104] [2572.19]
[2760.49949166] [2761.58]
[2886.77702411] [2884.7]
[2810.75135173] [2814.2]
[2904.37010739] [2905.93]
[2895.34963659] [2897.34]
[2513.29668899] [2515.07]
[2457.82317891] [2459.18]
[2295.41709188] [2293.64]
[2842.5084583] [2839.87]
[2469.23582317] [2469.59]
[2342.76741841] [2341.38]
[2396.97844073] [2396.77]
[2713.23756712] [2709.8]
[2430.96429662] [2428.52]
[2558.50234578] [2557.09]
[2900.11829239] [2901.13]
[2660.98620208] [2659.98]
[2564.71030806] [2564.65]
[2710.95906489] [2714.19]
[2637.71227171] [2635.5]
[2666.75449282] [2667.09]
[2466.45986793] [2459.43]
[2643.56930005] [2648.65]
[2840.15330515] [2839.12]
[2416.4720932] [2416.48]
[2573.04159484] [25

In [35]:
print(r2_score(y_test, testPredict))
print(mean_squared_error(y_test, testPredict))
print(mean_absolute_error(y_test, testPredict))

0.9998917705190015
3.8093462010753605
1.2602434466392418


In [20]:
print(confusion_matrix(y_test, np.argmax(testPredict, axis=1)))
print(f1_score(y_test, np.argmax(testPredict, axis=1), average='weighted'))

[[  4  25  22]
 [ 12  60  83]
 [ 27  78 114]]
0.4160729213403547
